#!/usr/bin/env bash
# _lib.sh — Shared library for Triton operational scripts.
#
# Source this file; do not execute directly.
# Requires: python3, flock (both expected in Flox environment).
#
# Provides:
#   lib::log, lib::warn, lib::err, lib::die   Leveled logging to stderr
#   lib::require_var, lib::require_pos_int     Input validation
#   lib::require_bool
#   lib::is_int, lib::is_num                   Type checks
#   lib::sha256_12                             First 12 hex of sha256
#   lib::slugify                               Safe path element
#   lib::flock_or_die                          Acquire flock with timeout
#   lib::write_env_atomically                  Atomic env-file write
#   lib::load_env_safe                         Python-based restricted parser
#   lib::load_env_trusted                      Direct source
#   lib::atomic_swap_dir                       Backup+swap for staged downloads
#   lib::restore_backup                        Recover interrupted swaps
#   lib::validate_model_name                   Single safe path element check

# Guard against double-sourcing.
[[ -n "${_LIB_SH_LOADED:-}" ]] && return 0
_LIB_SH_LOADED=1

# --- Verbosity ---
# 0=quiet  1=normal  2=verbose
TRITON_VERBOSITY="${TRITON_VERBOSITY:-1}"

# --- Logging ---

lib::log() {
  (( TRITON_VERBOSITY >= 1 )) && printf '%s\n' "$*" >&2 || true
}

lib::verbose() {
  (( TRITON_VERBOSITY >= 2 )) && printf '%s\n' "$*" >&2 || true
}

lib::warn() {
  printf 'WARNING: %s\n' "$*" >&2
}

lib::err() {
  printf 'ERROR: %s\n' "$*" >&2
}

lib::die() {
  lib::err "$@"
  exit 1
}

# --- Type checks ---

lib::is_int() {
  [[ "$1" =~ ^[0-9]+$ ]]
}

lib::is_num() {
  [[ "$1" =~ ^[0-9]+([.][0-9]+)?$ ]]
}

# --- Validation ---

lib::require_var() {
  local name="$1"
  local val="${!name:-}"
  [[ -n "$val" ]] || lib::die "Required env var is empty or unset: $name"
}

lib::require_pos_int() {
  local name="$1"
  local val="${!name:-}"
  [[ -n "$val" ]] || lib::die "Required env var is empty or unset: $name"
  lib::is_int "$val" || lib::die "$name must be a positive integer, got: $val"
  (( val > 0 )) || lib::die "$name must be > 0, got: $val"
}

lib::require_bool() {
  local name="$1"
  local val="${!name:-}"
  case "${val,,}" in
    true|false|1|0|yes|no) return 0 ;;
    *) lib::die "$name must be true/false/1/0/yes/no, got: $val" ;;
  esac
}

lib::is_truthy() {
  case "${1,,}" in
    true|1|yes) return 0 ;;
    *) return 1 ;;
  esac
}

# --- Hashing ---

lib::sha256_12() {
  python3 -c "import hashlib,sys;print(hashlib.sha256(sys.argv[1].encode('utf-8')).hexdigest()[:12])" "$1"
}

# --- Path helpers ---

lib::slugify() {
  printf '%s' "$1" | tr -cs 'A-Za-z0-9._-' '-'
}

lib::validate_model_name() {
  local name="$1"
  [[ -n "$name" ]] || lib::die "Model name is empty"
  [[ "$name" != */* ]] || lib::die "Model name must not contain '/': $name"
  [[ "$name" != *'\'* ]] || lib::die "Model name must not contain '\\': $name"
  [[ "$name" != "." && "$name" != ".." ]] || lib::die "Model name must not be '.' or '..': $name"
  [[ "$name" != *$'\n'* && "$name" != *$'\r'* && "$name" != *$'\t'* ]] || lib::die "Model name must not contain control whitespace"
}

# --- Locking ---

lib::flock_or_die() {
  local lockfile="$1"
  local timeout="${2:-10}"
  local label="${3:-}"

  # Symlink / non-regular check
  if [[ -e "$lockfile" ]]; then
    [[ ! -L "$lockfile" ]] || lib::die "Lockfile is a symlink: $lockfile"
    [[ -f "$lockfile" ]] || lib::die "Lockfile is not a regular file: $lockfile"
  fi

  local old_umask
  old_umask="$(umask)"
  umask 077
  exec 9>>"$lockfile"
  if ! flock -w "$timeout" 9; then
    umask "$old_umask"
    lib::die "Lock timeout after ${timeout}s: ${label:-$lockfile}"
  fi
  umask "$old_umask"
}

# --- Env file I/O ---

lib::write_env_atomically() {
  # Usage: lib::write_env_atomically <env_file> <key=value pairs as args>
  # Example: lib::write_env_atomically /path/to/file "TRITON_MODEL=foo" "TRITON_MODEL_REPOSITORY=/bar"
  local env_file="$1"; shift

  local env_dir
  env_dir="$(dirname "$env_file")"
  mkdir -p "$env_dir"

  local old_umask tmp
  old_umask="$(umask)"
  umask 077
  tmp="$(mktemp "${env_file}.tmp.XXXXXX")"
  umask "$old_umask"

  {
    echo "# generated by triton-resolve-model"
    local pair
    for pair in "$@"; do
      local key="${pair%%=*}"
      local val="${pair#*=}"
      printf 'export %s=%q\n' "$key" "$val"
    done
  } >"$tmp"

  mv -f "$tmp" "$env_file"
  chmod 600 "$env_file" 2>/dev/null || true
}

lib::load_env_safe() {
  # Python-based restricted parser: KEY=VALUE, optional export, optional quotes.
  # No interpolation, no command substitution.
  local f="$1"

  local tmp
  tmp="$(mktemp -t triton_env_exports.XXXXXX)"

  local rc=0
  python3 - "$f" >"$tmp" <<'PY' || rc=$?
import sys, re, shlex

path = sys.argv[1]
out = []

line_re = re.compile(r'^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$')

def parse_quoted(rest: str):
    q = rest[0]
    i = 1
    buf = []
    if q == "'":
        while i < len(rest):
            c = rest[i]
            if c == "'":
                i += 1
                break
            buf.append(c)
            i += 1
        else:
            raise SystemExit("Unterminated single-quoted value")
        return "".join(buf), rest[i:]
    while i < len(rest):
        c = rest[i]
        if c == '"':
            i += 1
            break
        if c == '\\':
            i += 1
            if i >= len(rest):
                buf.append('\\')
                break
            e = rest[i]
            if e == 'n': buf.append('\n')
            elif e == 't': buf.append('\t')
            elif e == '"': buf.append('"')
            elif e == '\\': buf.append('\\')
            else: buf.append(e)
            i += 1
            continue
        buf.append(c)
        i += 1
    else:
        raise SystemExit("Unterminated double-quoted value")
    return "".join(buf), rest[i:]

def strip_comment(s: str) -> str:
    m = re.match(r'^(.*?)(?:\s+#.*)?$', s)
    return (m.group(1) if m else s).rstrip()

with open(path, 'r', encoding='utf-8') as fh:
    for raw in fh:
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        m = line_re.match(line)
        if not m:
            raise SystemExit(f"Unsupported env line: {raw.rstrip()}")
        key, rest = m.group(1), m.group(2).lstrip()
        if rest.startswith(("'", '"')):
            val, tail = parse_quoted(rest)
            tail = tail.strip()
            if tail and not tail.startswith('#'):
                raise SystemExit(f"Unexpected trailing chars: {raw.rstrip()}")
        else:
            val = strip_comment(rest)
        out.append(f"export {key}={shlex.quote(val)}")

sys.stdout.write("\n".join(out) + ("\n" if out else ""))
PY

  if (( rc != 0 )); then
    rm -f "$tmp"
    return "$rc"
  fi

  set -a; set +u
  # shellcheck disable=SC1090
  source "$tmp"
  set -u; set +a
  rm -f "$tmp"
}

lib::load_env_trusted() {
  local f="$1"
  set -a; set +u
  # shellcheck disable=SC1090
  source "$f"
  set -u; set +a
}

# --- Directory swap ---

lib::restore_backup() {
  local target="$1"
  [[ -e "$target" ]] && return 0

  local newest
  newest="$(ls -td "${target}.bak."* 2>/dev/null | head -n 1 || true)"
  if [[ -n "$newest" && -e "$newest" ]]; then
    lib::warn "Target missing; restoring backup $(basename "$newest")"
    mv "$newest" "$target"
  fi
}

lib::atomic_swap_dir() {
  local staged="$1"
  local target="$2"

  lib::restore_backup "$target"

  local backup="${target}.bak.${RANDOM}${RANDOM}"
  if [[ -e "$target" ]]; then
    mv "$target" "$backup"
  fi

  if mv "$staged" "$target"; then
    [[ -e "$backup" ]] && rm -rf "$backup"
    return 0
  fi

  [[ -e "$backup" ]] && mv "$backup" "$target" || true
  return 1
}

# --- Misc ---

lib::run_to_log() {
  local log="$1"; shift
  : >"$log"
  "$@" >>"$log" 2>&1
}
